---
- name: Installing MySQL 5.7
  hosts: aws
  vars:
    root_user: root
    root_password: shahrukh@123
    mysql_user: bimex
    mysql_password: bimex@123
    db_name: bimex
    unix_socket: /var/run/mysqld/mysqld.sock 
  become: true
  tasks:
   - apt: update_cache=yes

   - name: Adding public key MySQL from ubuntu server
     apt_key:
        keyserver: keyserver.ubuntu.com
        id: 467B942D3A79BD29

   - name: Adding MySQL 5.7 apt repository
     apt_repository:
        repo: 'deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7'
        state: present
        
   - name: Installing MYSQL client 5.7
     apt:
        name: mysql-client=5.7*
        state: present

   - name: Installing mysql server 5.7
     apt:
        name: mysql-server=5.7*
        state: present
   - name: Installing pip 
     apt:
         name: python3-pip
         state: present

   - name: Making sure pymysql is present
     pip:
        name: pymysql
        state: present

   - name: Setting up MySQL root password
     mysql_user:
           login_host: 'localhost'
           login_user: '{{ root_user }}'
           login_password: "{{ root_password }}"
           login_unix_socket: '{{ unix_socket }}'
           name: '{{ root_user }}'
           password: "{{ root_password }}"
           state: present
           priv: '*.*:ALL,GRANT'

   - name: Creating a Database for bimex
     mysql_db:
           name: "{{ db_name }}"
           state: present
           login_unix_socket: '{{ unix_socket }}'
           login_user: '{{ root_user }}'
           login_password: "{{ root_password }}"
         
   - name: Setting up MySQL user & password
     mysql_user:
           name: '{{ mysql_user }}'
           password: "{{ mysql_password }}"
           host: '%'
           login_unix_socket: '{{ unix_socket }}'
           login_user: '{{ root_user }}'
           login_password: "{{ root_password }}"
           priv: "{{ db_name }}.{{ mysql_user }}:ALL,GRANT"
